### PR TITLE
Removed venv, added .gitignore

### PR DESCRIPTION
**Pull request by dheerajck**
Also you shouldnt add your env files to github

### CODE REVIEW

**Comment by Sangeeth123sj** [comment]
Kept it for beginner devs in the group to be able to use virtual environment easier and transition slowly.
But alright, the beginning devs seem to be working on frontend pages only so yeah merging this pull request.

**Comment by dheerajck** [comment]
1 - did you mean closed instead of merge
2 - adding venv to github doesnt help others in anyway, its infact useless for others
3 - encouraging bad practices doesnt help anyone, neither does adding secret keys to github

**Comment by dheerajck** [comment]
Remove sensitive data from github: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

Removing sensitive data with another commit doesnt help, you should also consider revoking api keys leaked even if you properly remove it

**Comment by Sangeeth123sj** [comment]
who is this clown?

**Pull request closed without merging**
